import Link from "next/link";
import { ArrowUpRight, Database, CircleAlert } from "lucide-react";
import type { AppSummary } from "@/lib/account/types";
import type { Product } from "@/lib/products";
export function ScopeError() { return <div className="card p-8"><h1 className="text-2xl font-semibold">Workspace unavailable</h1><p className="mt-3 text-muted">Choose a workspace you belong to, or view your personal account.</p><Link href="/?workspace=personal" className="btn-primary mt-6">View personal account</Link></div>; }
export function AppSummaryCard({ summary, product }: { summary: AppSummary; product?: Product }) {
  const ready=summary.status==="ready"||summary.status==="empty";
  return <article className="card flex flex-col p-5" data-product={summary.productKey}><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{product?.name??summary.productKey}</h3><span className={`rounded-full px-2 py-1 text-[10px] font-medium uppercase tracking-wider ${ready?"bg-accent/10 text-accent":"bg-panel-2 text-muted"}`}>{ready?"Connected":summary.status==="denied"?"No access":"Summary unavailable"}</span></div>{ready?<><div className="mt-5 flex flex-wrap gap-6">{summary.metrics.map(m=><div key={m.label}><p className="text-2xl font-semibold tracking-tight">{m.unit==="bytes"?formatBytes(m.value):m.value.toLocaleString()}</p><p className="mt-1 text-xs text-muted">{m.label}</p></div>)}</div>{summary.status==="empty"&&<p className="mt-4 text-sm text-muted">No records in this view yet.</p>}<ul className="mt-5 divide-y divide-line">{summary.recent.map(r=><li key={`${r.type}-${r.id}`} className="py-3"><a href={r.url} className="flex items-center justify-between gap-3 text-sm hover:text-accent"><span className="truncate">{r.title}</span><ArrowUpRight className="shrink-0" size={14} aria-hidden="true"/></a><p className="mt-1 text-xs text-muted">{r.type} · {new Date(r.updatedAt).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</p></li>)}</ul></>:<p className="mt-4 flex items-start gap-2 text-sm leading-relaxed text-muted"><CircleAlert size={16} className="mt-0.5 shrink-0" aria-hidden="true"/>{summary.status==="denied"?"This app has not granted access in this view.":"Summary unavailable — open the app to view your data"}</p>}<div className="mt-auto pt-5"><a href={summary.entryUrl} className="flex items-center gap-2 text-sm font-medium text-accent">Open {product?.name??"app"}<ArrowUpRight size={14} aria-hidden="true"/></a>{summary.workspaceEntry==="choose-in-app"&&summary.scope.kind==="workspace"&&<p className="mt-2 text-[11px] text-muted">Choose your workspace in the app.</p>}</div></article>;
}
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1024*1024)return `${(value/1024).toFixed(1)} KB`;return `${(value/1024/1024).toFixed(1)} MB`}
export function EmptyData() { return <div className="card p-8 text-center"><Database size={28} className="mx-auto text-muted" aria-hidden="true"/><h2 className="mt-4 font-semibold">Your data will appear here</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-muted">Open an AXXES app to start working. As app summaries become available, you can find your records here.</p><a href="/apps" className="btn-ghost mt-5">Explore AXXES apps</a></div>; }
