"use client";
import {useRouter} from "next/navigation";
import {useState} from "react";
import {authClient} from "@/lib/auth-client";
import {Alert,Button,Field,inputClass} from "@/components/ui";
import {revokeAccountSession,revokeOtherAccountSessions} from "@/app/(account)/security/actions";
export type DeviceInfo={id:string;current:boolean;userAgent:string|null;createdAt:string;updatedAt:string};
function describeDevice(ua:string|null){if(!ua)return "Unknown device";const browser=/Edg\//.test(ua)?"Edge":/Chrome\//.test(ua)?"Chrome":/Firefox\//.test(ua)?"Firefox":/Safari\//.test(ua)?"Safari":"Browser";const os=/iPhone|iPad/.test(ua)?"iOS":/Android/.test(ua)?"Android":/Mac OS X/.test(ua)?"macOS":/Windows/.test(ua)?"Windows":/Linux/.test(ua)?"Linux":"";return os?`${browser} on ${os}`:browser}
export function SecuritySettings({devices}:{devices:DeviceInfo[]}){
 const router=useRouter(),[pw,setPw]=useState({current:"",next:""}),[busy,setBusy]=useState<string|null>(null),[pwMessage,setPwMessage]=useState<{tone:"success"|"error";text:string}|null>(null),[deviceMessage,setDeviceMessage]=useState<{tone:"success"|"error";text:string}|null>(null);
 async function password(e:React.FormEvent){e.preventDefault();setBusy("password");setPwMessage(null);try{const {error}=await authClient.changePassword({currentPassword:pw.current,newPassword:pw.next,revokeOtherSessions:true});if(error)setPwMessage({tone:"error",text:error.message??"Your password could not be changed."});else{setPw({current:"",next:""});setPwMessage({tone:"success",text:"Password changed. Other devices were signed out."});router.refresh()}}catch{setPwMessage({tone:"error",text:"Your password could not be changed. Try again."})}finally{setBusy(null)}}
 async function revoke(id:string){setBusy(id);setDeviceMessage(null);try{const result=id==="others"?await revokeOtherAccountSessions():await revokeAccountSession(id);setDeviceMessage(result.ok?{tone:"success",text:id==="others"?"Other devices signed out.":"Device signed out."}:{tone:"error",text:result.error});if(result.ok)router.refresh()}catch{setDeviceMessage({tone:"error",text:"The device could not be signed out. Try again."})}finally{setBusy(null)}}
 return <div className="space-y-6"><form onSubmit={password} className="card space-y-5 p-6"><h2 className="text-lg font-semibold">Change password</h2><p className="text-sm text-muted">Changing your password signs out your other AXXES devices.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Current password"><input type="password" autoComplete="current-password" required value={pw.current} onChange={e=>setPw({...pw,current:e.target.value})} className={inputClass}/></Field><Field label="New password" hint="At least 8 characters."><input type="password" autoComplete="new-password" required minLength={8} value={pw.next} onChange={e=>setPw({...pw,next:e.target.value})} className={inputClass}/></Field></div>{pwMessage&&<Alert tone={pwMessage.tone}>{pwMessage.text}</Alert>}<Button type="submit" disabled={!!busy}>{busy==="password"?"Changing…":"Change password"}</Button></form><section className="card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Your devices</h2><p className="mt-1 text-sm text-muted">Active sessions shared across AXXES apps.</p></div>{devices.some(d=>!d.current)&&<Button variant="secondary" onClick={()=>revoke("others")} disabled={!!busy}>Sign out other devices</Button>}</div>{deviceMessage&&<div className="mt-4"><Alert tone={deviceMessage.tone}>{deviceMessage.text}</Alert></div>}<ul className="mt-4 divide-y divide-line">{devices.map(d=><li key={d.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><p className="text-sm font-medium">{describeDevice(d.userAgent)}{d.current&&<span className="ml-3 text-xs font-normal text-accent">This device</span>}</p><p className="mt-1 text-xs text-muted">Last active {new Date(d.updatedAt).toLocaleDateString("en-US")} · Signed in {new Date(d.createdAt).toLocaleDateString("en-US")}</p></div>{!d.current&&<Button variant="danger" onClick={()=>revoke(d.id)} disabled={!!busy}>Sign out</Button>}</li>)}</ul></section></div>
}
