import {generateKeyPair,exportJWK} from 'jose';
import {randomUUID} from 'node:crypto';
import type {Code,Grant,Key,Store} from './service';
export type Connection={query:(text:string,values?:unknown[])=>Promise<{rows:Record<string,unknown>[];rowCount?:number|null}>};
export type Database=Connection&{transaction<T>(work:(connection:Connection)=>Promise<T>):Promise<T>};
const date=(v:unknown)=>v instanceof Date?v:new Date(String(v));
function grant(row:Record<string,unknown>):Grant{return {id:String(row.id),userId:String(row.user_id),clientId:String(row.client_id),scopes:String(row.scopes),nonce:String(row.nonce),authTime:date(row.auth_time),accessHash:String(row.access_token),refreshHash:String(row.refresh_token),accessExpiresAt:date(row.access_token_expires_at),refreshExpiresAt:date(row.refresh_token_expires_at)}};
const select=`SELECT t.*,m.nonce,m.auth_time FROM oauth_access_token t JOIN workspace_oidc_token_metadata m ON m.token_id=t.id`;
export function createStore(db:Database,accountAllowed:(id:string)=>Promise<boolean>=async()=>true):Store{return {
 async user(id){if(!await accountAllowed(id))return null;const row=(await db.query('SELECT id,name,email,email_verified FROM "user" WHERE id=$1',[id])).rows[0];return row?{id:String(row.id),name:String(row.name),email:String(row.email),emailVerified:row.email_verified===true}:null;},
 async createCode(c){await db.query('INSERT INTO workspace_oidc_codes(code_hash,user_id,client_id,redirect_uri,challenge,scopes,nonce,auth_time,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',[c.codeHash,c.userId,c.clientId,c.redirectUri,c.challenge,c.scopes,c.nonce,c.authTime,c.expiresAt]);},
 async consumeCode(hash){const row=(await db.query('DELETE FROM workspace_oidc_codes WHERE code_hash=$1 RETURNING *',[hash])).rows[0];return row?{codeHash:String(row.code_hash),userId:String(row.user_id),clientId:String(row.client_id),redirectUri:String(row.redirect_uri),challenge:String(row.challenge),scopes:String(row.scopes),nonce:String(row.nonce),authTime:date(row.auth_time),expiresAt:date(row.expires_at)}:null;},
 async createGrant(g){await db.transaction(async q=>{await q.query('INSERT INTO oauth_access_token(id,access_token,refresh_token,access_token_expires_at,refresh_token_expires_at,client_id,user_id,scopes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',[g.id,g.accessHash,g.refreshHash,g.accessExpiresAt,g.refreshExpiresAt,g.clientId,g.userId,g.scopes]);await q.query('INSERT INTO workspace_oidc_token_metadata(token_id,nonce,auth_time) VALUES ($1,$2,$3)',[g.id,g.nonce,g.authTime]);});},
 async rotateGrant(hash,clientId,accessHash,refreshHash,accessExpiresAt){return db.transaction(async q=>{
  const row=(await q.query(select+' WHERE t.refresh_token=$1 AND t.client_id=$2 FOR UPDATE OF t',[hash,clientId])).rows[0];
  if(!row){const reused=(await q.query('SELECT token_id FROM workspace_oidc_refresh_history WHERE token_hash=$1 AND client_id=$2 AND expires_at>now()',[hash,clientId])).rows[0];if(reused)await q.query('DELETE FROM oauth_access_token WHERE id=$1 AND client_id=$2',[reused.token_id,clientId]);return null;}
  const g=grant(row);if(!await accountAllowed(g.userId))return null;if(g.refreshExpiresAt<=new Date()||!g.scopes.split(' ').includes('offline_access'))return null;
  await q.query('INSERT INTO workspace_oidc_refresh_history(token_hash,token_id,client_id,expires_at) VALUES ($1,$2,$3,$4) ON CONFLICT DO NOTHING',[hash,g.id,clientId,g.refreshExpiresAt]);
  await q.query('UPDATE oauth_access_token SET access_token=$2,refresh_token=$3,access_token_expires_at=$4,updated_at=now() WHERE id=$1',[g.id,accessHash,refreshHash,accessExpiresAt]);
  return {...g,accessHash,refreshHash,accessExpiresAt};
 });},
 async revoke(hash,clientId){await db.transaction(async q=>{await q.query('DELETE FROM oauth_access_token WHERE client_id=$2 AND id IN (SELECT token_id FROM workspace_oidc_token_metadata) AND (access_token=$1 OR refresh_token=$1 OR id IN (SELECT token_id FROM workspace_oidc_refresh_history WHERE token_hash=$1 AND client_id=$2))',[hash,clientId]);});},
 async findAccess(hash){const row=(await db.query(select+' WHERE t.access_token=$1',[hash])).rows[0];return row&&await accountAllowed(String(row.user_id))?grant(row):null;},
 async key(){return db.transaction(async q=>{await q.query('SELECT pg_advisory_xact_lock(723809423)');const existing=(await q.query('SELECT * FROM workspace_oidc_keys WHERE expires_at>now() ORDER BY created_at DESC LIMIT 1')).rows[0];if(existing)return {id:String(existing.id),privateJwk:existing.private_jwk as Key['privateJwk'],publicJwk:existing.public_jwk as Key['publicJwk']};const id=randomUUID(),pair=await generateKeyPair('RS256',{extractable:true,modulusLength:2048});const privateJwk={...await exportJWK(pair.privateKey),kid:id,alg:'RS256',use:'sig'},publicJwk={...await exportJWK(pair.publicKey),kid:id,alg:'RS256',use:'sig'};await q.query("INSERT INTO workspace_oidc_keys(id,private_jwk,public_jwk,expires_at) VALUES ($1,$2,$3,now()+interval '30 days')",[id,JSON.stringify(privateJwk),JSON.stringify(publicJwk)]);await q.query("DELETE FROM workspace_oidc_codes WHERE expires_at<now(); DELETE FROM workspace_oidc_refresh_history WHERE expires_at<now(); DELETE FROM workspace_oidc_keys WHERE expires_at<now()-interval '1 day'");return {id,privateJwk,publicJwk};});},
 async jwks(){await this.key();return (await db.query("SELECT public_jwk FROM workspace_oidc_keys WHERE expires_at>now()-interval '1 hour'")).rows.map(r=>r.public_jwk as Key['publicJwk']);}
};}
