import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { getAccountView, type AccountSearch } from "@/lib/account/page-view";
import { confirmedApps } from "@/lib/account/view";
import { getProducts } from "@/lib/products";
import { AppSummaryCard, EmptyData, ScopeError } from "@/components/account/app-summary";
export default async function AccountHome({searchParams}:{searchParams:AccountSearch}){
  const result=await getAccountView(searchParams);if(!result.ok)return <ScopeError/>;
  const o=result.overview,products=await getProducts(),apps=confirmedApps(o.apps,o.connections),scopeId=o.scope.kind==="workspace"?o.scope.id:null,scope=scopeId?o.workspaces.find(w=>w.id===scopeId):null;
  const q=`?workspace=${o.scope.kind==="personal"?"personal":o.scope.id}`;
  const available=o.apps.filter(a=>a.status==="ready"||a.status==="empty").length;
  return <><p className="font-mono text-[10px] uppercase tracking-[0.24em] text-accent">Your AXXES account</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Welcome back, {o.profile.name.split(" ")[0]}</h1><p className="mt-3 text-sm text-muted">Your work, your data, and your account. All in one place.</p><div className="mt-8 grid grid-cols-2 gap-3 xl:grid-cols-4">{[{label:"Workspaces",value:o.workspaces.length,href:"/workspaces"},{label:"Apps in this view",value:apps.length,href:"/data"},{label:"Identity connections",value:o.connections.filter(c=>c.kind==="identity").length,href:"/connections"},{label:"Account security",value:"Manage",href:"/security"}].map(s=><Link key={s.label} href={`${s.href}${q}`} className="card p-5 transition hover:border-accent/40"><p className="text-xs text-muted">{s.label}</p><p className="mt-3 text-2xl font-semibold tracking-tight">{s.value}</p></Link>)}</div><section className="mt-10"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-semibold">Continue working</h2><p className="mt-1 text-xs text-muted">{scope?.name??"Personal"} · Accessible records and management links</p></div><Link href={`/data${q}`} className="flex items-center gap-1 text-sm text-accent">View data<ArrowUpRight size={15}/></Link></div>{apps.length?<div className="grid gap-4 xl:grid-cols-2">{apps.map(a=><AppSummaryCard key={a.productKey} summary={a} product={products.find(p=>p.key===a.productKey)}/>)}</div>:<EmptyData/>}</section><section className="card mt-6 flex flex-col justify-between gap-5 p-5 sm:flex-row sm:items-center"><div><h2 className="font-semibold">{scope?`${scope.name} workspace`:"Personal account"}</h2><p className="mt-2 text-sm text-muted">{scope?`Your role: ${scope.role}. Plan details are not available here yet.`:"Your profile, connections and devices belong to you across AXXES."}</p></div><Link href={`${scope?"/workspaces":"/profile"}${q}`} className="btn-ghost shrink-0">{scope?"View workspace":"Manage profile"}</Link></section><div className="mt-6 flex flex-wrap items-center justify-between gap-3 text-xs text-muted"><p>{available} of {o.apps.length} app summaries available in this view.</p><Link href={`/data${q}`} className="text-accent">View coverage and all apps</Link></div><section className="mt-10"><h2 className="text-xl font-semibold">Explore AXXES</h2><p className="mt-2 text-sm text-muted">Find more tools for your business in the current product directory.</p><Link href="/apps" className="btn-ghost mt-4">All {products.length} products<ArrowUpRight size={16}/></Link></section></>;
}
